#
# GitHub Actions manual workflow.
#
# The main purpose of this workflow is to allow us (developers) to make
# quick changes to CI jobs without having to push them into the repository.
# This workflow file serves as a template that we can modify anytime that we
# need to experiment with new CI changes. The process to follow in those
# cases is fairly simple:
#
# 1. Create a topic-branch where to commit your changes (e.g. dev-branch).
#
# 2. Modify this file so that it looks as close as possible to the desired CI
#    job that will be eventually merged to the repo. Let's refer to this workflow
#    as a 'testing' workflow to differentiate it from the one in the 'master'
#    branch.
#
# 3. Head over to the 'actions' portal within the repo we're working on, and
#    click on the 'Manual Workflow". Then find the button "Run workflow" and
#    click on it. Finally, choose the branch over which our 'testing' workflow
#    was submitted.
#
# 4. Github will now run this latest 'testing' version of the workflow, and
#    not the one being stored in the master branch.
#
# 5. Repeat above cycle as many times as required, and when done, place the
#    workflow changes in a new file; do not make permanent changes to this
#    file as this one is just expected to serve as a template to ease our
#    live during CI definition & testing.
#

name: Manual Workflow

# Runs on-demand
on:
  workflow_dispatch:
    inputs:
      body:
        default: ""
      test:
        default: "false"

#jobs:
#  sysbox_pkg_test:
#    runs-on: [self-hosted, Linux, X64, "${{ matrix.distro }}"]
#    strategy:
#      fail-fast: false
#    steps:
#      - name: precheckout-cleanup
#        run: |
#          sudo rm -rf *
#      - name: checkout
#        uses: actions/checkout@v2

jobs:
  docker:
    runs-on: [self-hosted, Linux, X64, my-label]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: bbachi/dockerfile-examples
          path: dockerfile-examples
          ssh: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzOM/+jcYNEtJohXUTTv055G9TnU9CBhxuARLT6ZrgBBG/I4jJT1JimJJcNvVEoCEhEqP3/r9diQyKlqNqi173hZTlOPIqxt3EmB0qCDSP0wjRNiFjpyP/jxxNgctgo0xlbsJDaFxsxnPcE7+dmXVVubA4JlaiE7F5RhTcK26JPvTjveTJdvAkUMR20bQ7trg/wXetzINyL2w2FqLBF/MKos/lHxcI2zn86dj56hnDD5me40m5v1PwcrU5HqsF8R65sZhReRH98IahRg1eVwz9/3s6ccg9j2OoRml336UvOCbu/7srHc0vcC1lPzIMetf4R3JltCaJKgziLONHd6y6S9gaBn/k8QG79NJBMpSPAZeEY47rNlk4OkDhGDJvAJPVO+z+lpBfRD6glGaWJfO+EeWgfp/VDd+O0WSQ8VFS6vV3PU5f5kRgAPBboXEBK47Lkw0AbL7a8Yjvp87/roZHQF1VVtpZtEt9AyS+ZVdWxIENtoP6P3NhOTqA7i7APfE= vagrant@ubuntu-focal-vm-2'

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: dockerfile-examples
          file: dockerfile-examples/Dockerfile9
          load: true
          tags: nestybox/sysbox-runner-app-tester:latest