#
# GitHub Actions manual workflow.
#
# The main purpose of this workflow is to allow us (developers) to make
# quick changes to CI jobs without having to push them into the repository.
# This workflow file serves as a template that we can modify anytime that we
# need to experiment with new CI changes. The process to follow in those
# cases is fairly simple:
#
# 1. Create a topic-branch where to commit your changes (e.g. dev-branch).
#
# 2. Modify this file so that it looks as close as possible to the desired CI
#    job that will be eventually merged to the repo. Let's refer to this workflow
#    as a 'testing' workflow to differentiate it from the one in the 'master'
#    branch.
#
# 3. Head over to the 'actions' portal within the repo we're working on, and
#    click on the 'Manual Workflow". Then find the button "Run workflow" and
#    click on it. Finally, choose the branch over which our 'testing' workflow
#    was submitted.
#
# 4. Github will now run this latest 'testing' version of the workflow, and
#    not the one being stored in the master branch.
#
# 5. Repeat above cycle as many times as required, and when done, place the
#    workflow changes in a new file; do not make permanent changes to this
#    file as this one is just expected to serve as a template to ease our
#    live during CI definition & testing.
#

name: Manual Workflow

# Runs on-demand
on:
  workflow_dispatch:
    inputs:
      body:
        default: ""
      test:
        default: "false"

jobs:
  docker:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: bbachi/dockerfile-examples
          path: dockerfile-examples
          ssh: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbHblNET0aO8OddoyyEklyNEhQxR57Ny7WVHv/h+hGhJuhj8NTFhRZI+W0ciLlpo2bNi4k6GDoXUU7G3n9NuGtK6ktUzyXZ8yeJ4QYZm8eoqPSE0QyoUP+OEyeFWq9nvdqe5MsbWgzFLjzDByFzTnsk3lvMgi0InzU8XYF0EIOJzM/1Bw3SRUJM0maoDZXNwcqM7SNyYCzHQibSZF742qYcnjcV+0u0jn7Uq1MT9bCGmSm1qnuynb6l9DLlIAXSB+FvupKzDDarqH7Lp7ZcX8Y3qB2rZPiR+lZRXVbKP2NSlyUqDyKaOa0iK7tA3NC+G0JJfQyNJqJLoBkXotIeDinOJAKYavuj7t4wccXyKZqfm3FuKUhVx0mgvltdtAT05I/fadpuOw31JIqBefDHrKPV7TfdfCUFBw+kv6olfKU3qHMLUiwoj3FofmRJh76KGJbDm3wwBIqyeUL9gVkZ5DvR2VHOF6TgpH0X6iVHvl1iiESn0EgCTJWN4bY+7ost+M= rmolina@rodny-dev-vm-2'
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: dockerfile-examples
          file: dockerfile-examples/Dockerfile9
          load: true
          tags: nestybox/sysbox-runner-app-tester:latest
